src/Entity/Sujet.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\SujetRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=SujetRepository::class)
 * @UniqueEntity(fields={"titre"}, message="Un sujet a déjà été créé avec ce titre, nous vous invitons à modifier le titre ou effectuer une recherche pour voir les réponses.")
 */
class Sujet
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="sujets")
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToOne(targetEntity=User::class, inversedBy="sujet", cascade={"persist", "remove"})
     */
    private $author;

    

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="sujets")
     */
    private $Authors;

    /**
     * @ORM\JoinColumn(name="comments_id", referencedColumnName="id", onDelete="CASCADE")
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="sujet", cascade={"remove"})
     */
    private $comments;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $averti;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $desable;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getAutheur(): ?string
    {
        return $this->autheur;
    }

    public function setAutheur(?string $autheur): self
    {
        $this->autheur = $autheur;

        return $this;
    }

    public function getAuteur(): ?string
    {
        return $this->auteur;
    }

    public function setAuteur(?string $auteur): self
    {
        $this->auteur = $auteur;

        return $this;
    }

    public function getAuthors(): ?User
    {
        return $this->Authors;
    }

    public function setAuthors(?User $Authors): self
    {
        $this->Authors = $Authors;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setSujet($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getSujet() === $this) {
                $comment->setSujet(null);
            }
        }

        return $this;
    }

    public function getAverti(): ?bool
    {
        return $this->averti;
    }

    public function setAverti(?bool $averti): self
    {
        $this->averti = $averti;

        return $this;
    }

    public function getDesable(): ?string
    {
        return $this->desable;
    }

    public function setDesable(?string $desable): self
    {
        $this->desable = $desable;

        return $this;
    }
}

templates/sujet/add.sujet.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un sujet{% endblock %}

{% block body %}
<div class="container">
{% include "partials/flash.html.twig" %}
        <h1 class="text-center py-3">Vous souhaitez ajouter un sujet sur notre forum ?</h1>
        <div class="div-registration">
            {{ form_start(form) }}
            
            {{form_widget(form)}}
            <div class="row justify-content-center pb-3 inscription">
                <div class="col">
                    <button type="submit" class="btn btn-success d-block mx-auto my-3">Ajouter le sujet</button>
                </div>
            </div>
            {{form_end(form)}}
        </div>
    </div>
{% endblock %}

templates/sujet/edit.sujet.html.twig
{% extends "base.html.twig" %}
{% block meta_description %}
         <meta name="description" content="Page de modification de mon profil" />   
        {% endblock %}
{% block title %}Modification du profil{% endblock %}
{% block body %}
    <div class="container">
        {% include "partials/flash.html.twig" %}
        <div class="p-3">
            <h2 class="text-center pt-3">Modification du sujet : {{sujet.titre}}</h2>
            
            {{form_start(form)}}
           {{form_row(form.titre, {
            'attr': {
                'placeholder' : "Votre titre",
                'value' : sujet.titre
            }
        })}}
        {{form_row(form.contenu, {
            'attr': {
                'placeholder' : "Votre contenu",
                
            }
        })}}
           {{form_widget(form)}}
           
                <div class="row justify-content-center">
                    <div class="col pt-3">
                        <button type="submit" class="btn btn-success d-block mx-auto my-0">Enregistrer les modifications</button>
                    </div> 
            </div>
        </div>
        {{form_end(form)}}
        <script>
            document.getElementById('edit_sujet_contenu').innerHTML = '{{sujet.contenu}}';
        </script>
    </div>  
{% endblock %}

templates/sujet/send_email.html.twig
<h1>Bonjour {{sujet.authors.firstname}}</h1>
<p>Un utilisateur a répondu à un de vos sujet : {{sujet.titre}}</p>
<p>En répondant : {{comment.content}}</p>
<a href="{{absolute_url(path('show_sujet', {'titrecategory': sujet.category.slug,'slug': sujet.slug}))}}">Voir le sujet</a>
<br>
<a href="{{ absolute_url(path('desabonner', {"id": sujetID, 'token': registrationToken})) }}">
    Ne plus être averti des prochaines réponses
    </a>

templates/sujet/sujet.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos sujets{% endblock %}

{% block body %}
<div class="container-fluid">
                <h1 class="py-3"><b>Nos sujets</b></h1> 
                <div class="row">
                    {% for sujet in sujets %}
                    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 col-xl-4 my-3">
                        <div class="card mx-auto" style="width: 18rem;">
                            <img class="card-img-top" src="{{ asset("images/" ~ sujet.image) }}" alt="Card image cap" 
                            style="height:200px; width=100px; display:block">
                            <div class="card-body">
                                    <h5 class="card-title red">{{sujet.titre}}</h5>
                                    <p class="card-text">{{sujet.contenu}}</p>
                            </div>
                            <a href="{{path ('show_sujet', {'slug': sujet.slug}) }}" class="btn btn-tarif">Voir plus</a>  
                            </div>
                        </div>    
                    {% endfor %}
                </div>
            </div> 
            {% endblock %}